### ISSUE TITLE
add a favicon

### ISSUE THREAD

**Issue by gadanidis** [uoft-lgcu/lgcu.ca#22]
We can add a favicon (small image appearing next to the URL in browsers) to the website by adding a `favicon.ico` file to the repository. Any ideas for what that could be? Is the "don't die" wug readable at that size (/ will we not get sued if we use it)?

**Comment by fwilson-603** [comment]
I doubt the 'don't die' version would be readable. Any form of wug probably has a high likelihood of getting an annoying email from Gleason et al., and a very low likelihood of any actual legal consequences.

**Comment by gadanidis** [comment]
I made a topic on zulip to solicit suggestions.

**Comment by gadanidis** [comment]
I made the favicon say "BOUNDLESS" because I thought it was kind of funny and is fairly readable. We can always change it later if anyone doesn't like it.
