### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by fwilson-603** [uoft-lgcu/lgcu.ca#33]
Link to the issues reporting form in the footer is broken.

**Comment by fwilson-603** [comment]
(Assigning Tim to this issue because I'm pretty sure he wrote the form, and I can't seem to find where it's actually located)

**Comment by gadanidis** [comment]
It looks like this is a problem with the gitreports site — every page on the site returns the same error.

https://gitreports.com/

Maybe whoever wrote it has decided to stop maintaining it? We can wait a bit to see if it comes back online and if not we can look into another solution...

At 10:27 EST on 2022-02-03 (Thu), Fiona wrote:
> (Assigning Tim to this issue because I'm pretty sure he wrote the form, and I can't seem to find where it's actually located)
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/uoft-lgcu/lgcu.ca/issues/33#issuecomment-1029105769
> You are receiving this because you were assigned.
> 
> Message ID: ***@***.***>

-- 
Tim Gadanidis
e: ***@***.***
w: gadanidis.ca

**Comment by gadanidis** [comment]
For reference, the footer is in `_includes/footer.html`

**Comment by gadanidis** [comment]
Issue at the gitreports repo for reference: https://github.com/schneidmaster/gitreports.com/issues/240

**Comment by fwilson-603** [comment]
Okay, thanks for looking into that. I was able to find the link in the footer, but since it linked to an external page, I got stuck at that point. If gitreports goes back up (and therefore we don't have to find an alternative), we should add some info to the wiki about how to maintain/alter the issues form.

**Comment by gadanidis** [comment]
Fixed in 3f6449f by suggesting to email the website committee members instead — we can just set up an issue manually when/if we get feedback by email.
