### ISSUE TITLE
Last update

### ISSUE THREAD

**Issue by justinrleung** [uoft-lgcu/lgcu.ca#37]
The footer doesn't update properly with the date of last update. For example, on the [How-To page](https://lgcu.ca/how-to/), it shows up as 14 March 2021 even though I've updated the page just today.

**Comment by gadanidis** [comment]
Right now, the date has to be updated manually. It's in the YAML header of the file:

```
---
layout: page
title: How‑To
modified: 2021-03-14
permalink: /how-to/
---
```

It could be worth looking into doing this automatically somehow, though.

**Comment by justinrleung** [comment]
Ah, I see. I imagine it would need to check several things because it's not just the page itself, but also the dependent data files.
