### ISSUE TITLE
Update committees for 2024-25

### ISSUE THREAD

**Issue by gadanidis** [uoft-lgcu/lgcu.ca#38]
The committee info needs to be updated for this academic year.

**Comment by gadanidis** [comment]
Info on how to update this data:

https://github.com/uoft-lgcu/lgcu.ca/wiki/Maintaining-and-Updating-the-Site#regular-updates

**Comment by gadanidis** [comment]
https://docs.google.com/spreadsheets/d/1uShfUKY-d6-anuwr7c5dJNWPN5DDOGUyzqpuwDo2LHI/edit?usp=sharing

**Comment by jchowgw** [comment]
I've tried to update the people, but something is not working and I keep getting the same message: 
  | Deploy Jekyll site to Pages, Attempt #2 / buildFailed in 16 seconds

**Comment by jchowgw** [comment]
> I've tried to update the people, but something is not working and I keep getting the same message:   | Deploy Jekyll site to Pages, Attempt #2 / buildFailed in 16 seconds

Also this error message:
 Liquid Exception: no implicit conversion of String into Integer in pages/committees.md

**Comment by gadanidis** [comment]
I had a look, and this error is because for the `secretary` role, there is a hyphen before Christy's entry. In YAML, using hyphens indicate that there are multiple items (a list/array), but the code that accesses the `secretary` role is checking for a single value, not multiple values. Removing the hyphen fixes this; I've done so in [a733364](https://github.com/uoft-lgcu/lgcu.ca/commit/a733364c750c4a3ad362fd8eae7482395069d5a9). Everything else looks good, thanks for doing the update!

**Comment by gadanidis** [comment]
I've added error handling to [lingsite_filter.rb](https://github.com/uoft-lgcu/lgcu.ca/blob/main/_plugins/lingsite_filter.rb) in [ee38804](https://github.com/uoft-lgcu/lgcu.ca/commit/ee38804e5b78b04d2a0fcca203e6aea3fbffd713) to attempt to automatically resolve errors like this, or at least display more informative error messages.
