### ISSUE TITLE
Add a description in `_config.yml`

### ISSUE THREAD

**Issue by gadanidis** [uoft-lgcu/lgcu.ca#40]
Currently we have the default description listed in `_config.yml`, which looks bad in search engines / links in social media apps, etc. We should replace it with an informative description of the LGCU site.

```
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
```

**Comment by gadanidis** [comment]
We want a description that says something about what our website actually is, like "The official website of the Linguistics Graduate Course Union at UofT."

**Comment by Xinyu-Liao** [comment]
I've updated a new description there!

**Comment by gadanidis** [comment]
Looks good to me, thanks! It now shows up in messenger apps, links on social media/search engines, etc.:

![image](https://github.com/user-attachments/assets/a78e78e7-d80d-4981-97c8-e7cbf104581d)
